package java.util;

public class Currency {

  private static Map<String, Currency> map;
  private static Map<String, Currency> countryToCurrency;

  static {
    map = new HashMap<String, Currency>(200) {

      {
        put("AFN", new Currency("AFN", 971, 2, "؋"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("ALL", new Currency("ALL", 8, 2, "L"));
        put("DZD", new Currency("DZD", 012, 2, "د.ج"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("AOA", new Currency("AOA", 973, 2, "Kz"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("ARS", new Currency("ARS", 032, 2, "$"));
        put("AMD", new Currency("AMD", 051, 2, "դր."));
        put("AWG", new Currency("AWG", 533, 2, "ƒ"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("AZN", new Currency("AZN", 944, 2, "m"));
        put("BSD", new Currency("BSD", 044, 2, "$"));
        put("BHD", new Currency("BHD", 48, 3, ".د.ب"));
        put("BDT", new Currency("BDT", 050, 2, "৳"));
        put("BBD", new Currency("BBD", 052, 2, "$"));
        put("BYN", new Currency("BYN", 933, 2, "Br"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("BZD", new Currency("BZD", 84, 2, "$"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("BMD", new Currency("BMD", 060, 2, "$"));
        put("INR", new Currency("INR", 356, 2, "₹"));
        put("BTN", new Currency("BTN", 064, 2, "Nu."));
        put("BOB", new Currency("BOB", 68, 2, "Bs."));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("BAM", new Currency("BAM", 977, 2, "КМ"));
        put("BWP", new Currency("BWP", 072, 2, "P"));
        put("NOK", new Currency("NOK", 578, 2, "kr"));
        put("BRL", new Currency("BRL", 986, 2, "R$"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("BND", new Currency("BND", 96, 2, "$"));
        put("BGN", new Currency("BGN", 975, 2, "лв"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("BIF", new Currency("BIF", 108, 0, "Fr"));
        put("CVE", new Currency("CVE", 132, 2, "Esc or $"));
        put("KHR", new Currency("KHR", 116, 2, "៛"));
        put("XAF", new Currency("XAF", 950, 0, "Fr"));
        put("CAD", new Currency("CAD", 124, 2, "$"));
        put("KYD", new Currency("KYD", 136, 2, "$"));
        put("XAF", new Currency("XAF", 950, 0, "Fr"));
        put("XAF", new Currency("XAF", 950, 0, "Fr"));
        put("CLP", new Currency("CLP", 152, 0, "$"));
        put("CNY", new Currency("CNY", 156, 2, "¥"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("COP", new Currency("COP", 170, 2, "$"));
        put("KMF", new Currency("KMF", 174, 0, "Fr"));
        put("CDF", new Currency("CDF", 976, 2, "Fr"));
        put("XAF", new Currency("XAF", 950, 0, "Fr"));
        put("NZD", new Currency("NZD", 554, 2, "$"));
        put("CRC", new Currency("CRC", 188, 2, "₡"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("HRK", new Currency("HRK", 191, 2, "kn"));
        put("CUP", new Currency("CUP", 192, 2, "$"));
        put("CUC", new Currency("CUC", 931, 2, "$"));
        put("ANG", new Currency("ANG", 532, 2, "ƒ"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("CZK", new Currency("CZK", 203, 2, "Kč"));
        put("DKK", new Currency("DKK", 208, 2, "kr"));
        put("DJF", new Currency("DJF", 262, 0, "Fr"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("DOP", new Currency("DOP", 214, 2, "$"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("EGP", new Currency("EGP", 818, 2, "ج.م"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("XAF", new Currency("XAF", 950, 0, "Fr"));
        put("ERN", new Currency("ERN", 232, 2, "Nfk"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("SZL", new Currency("SZL", 748, 2, "L"));
        put("ETB", new Currency("ETB", 230, 2, "Br"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("FKP", new Currency("FKP", 238, 2, "£"));
        put("DKK", new Currency("DKK", 208, 2, "kr"));
        put("FJD", new Currency("FJD", 242, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("XPF", new Currency("XPF", 953, 0, "Fr"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("XAF", new Currency("XAF", 950, 0, "Fr"));
        put("GMD", new Currency("GMD", 270, 2, "D"));
        put("GEL", new Currency("GEL", 981, 2, "ლ"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("GHS", new Currency("GHS", 936, 2, "₵"));
        put("GIP", new Currency("GIP", 292, 2, "£"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("DKK", new Currency("DKK", 208, 2, "kr"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("GTQ", new Currency("GTQ", 320, 2, "Q"));
        put("GBP", new Currency("GBP", 826, 2, "£"));
        put("GNF", new Currency("GNF", 324, 0, "Fr"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("GYD", new Currency("GYD", 328, 2, "$"));
        put("HTG", new Currency("HTG", 332, 2, "G"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("HNL", new Currency("HNL", 340, 2, "L"));
        put("HKD", new Currency("HKD", 344, 2, "$"));
        put("HUF", new Currency("HUF", 348, 2, "Ft"));
        put("ISK", new Currency("ISK", 352, 0, "kr"));
        put("INR", new Currency("INR", 356, 2, "₹"));
        put("IDR", new Currency("IDR", 360, 2, "Rp"));
        put("IRR", new Currency("IRR", 364, 2, "﷼"));
        put("IQD", new Currency("IQD", 368, 3, "ع.د"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("GBP", new Currency("GBP", 826, 2, "£"));
        put("ILS", new Currency("ILS", 376, 2, "₪"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("JMD", new Currency("JMD", 388, 2, "$"));
        put("JPY", new Currency("JPY", 392, 0, "¥"));
        put("GBP", new Currency("GBP", 826, 2, "£"));
        put("JOD", new Currency("JOD", 400, 3, "د.ا"));
        put("KZT", new Currency("KZT", 398, 2, "₸"));
        put("KES", new Currency("KES", 404, 2, "Sh"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("KPW", new Currency("KPW", 408, 2, "₩"));
        put("KRW", new Currency("KRW", 410, 0, "₩"));
        put("KWD", new Currency("KWD", 414, 3, "د.ك"));
        put("KGS", new Currency("KGS", 417, 2, "лв"));
        put("LAK", new Currency("LAK", 418, 2, "₭"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("LBP", new Currency("LBP", 422, 2, "ل.ل"));
        put("LSL", new Currency("LSL", 426, 2, "L"));
        put("ZAR", new Currency("ZAR", 710, 2, "R"));
        put("LRD", new Currency("LRD", 430, 2, "$"));
        put("LYD", new Currency("LYD", 434, 3, "ل.د"));
        put("CHF", new Currency("CHF", 756, 2, "Fr"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("MOP", new Currency("MOP", 446, 2, "P"));
        put("MKD", new Currency("MKD", 807, 2, "ден"));
        put("MGA", new Currency("MGA", 969, 2, "Ar"));
        put("MWK", new Currency("MWK", 454, 2, "MK"));
        put("MYR", new Currency("MYR", 458, 2, "RM"));
        put("MVR", new Currency("MVR", 462, 2, ".ރ"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("MUR", new Currency("MUR", 480, 2, "₨"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("MXN", new Currency("MXN", 484, 2, "$"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("MDL", new Currency("MDL", 498, 2, "L"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("MNT", new Currency("MNT", 496, 2, "₮"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("MAD", new Currency("MAD", 504, 2, "د.م."));
        put("MZN", new Currency("MZN", 943, 2, "MT"));
        put("MMK", new Currency("MMK", 104, 2, "Ks"));
        put("NAD", new Currency("NAD", 516, 2, "$"));
        put("ZAR", new Currency("ZAR", 710, 2, "R"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("NPR", new Currency("NPR", 524, 2, "₨"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("XPF", new Currency("XPF", 953, 0, "Fr"));
        put("NZD", new Currency("NZD", 554, 2, "$"));
        put("NIO", new Currency("NIO", 558, 2, "C$"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("NGN", new Currency("NGN", 566, 2, "₦"));
        put("NZD", new Currency("NZD", 554, 2, "$"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("NOK", new Currency("NOK", 578, 2, "kr"));
        put("OMR", new Currency("OMR", 512, 3, "ر.ع."));
        put("PKR", new Currency("PKR", 586, 2, "₨"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("PAB", new Currency("PAB", 590, 2, "B/."));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("PGK", new Currency("PGK", 598, 2, "K"));
        put("PYG", new Currency("PYG", 600, 0, "₲"));
        put("PEN", new Currency("PEN", 604, 2, "S/."));
        put("PHP", new Currency("PHP", 608, 2, "₱"));
        put("NZD", new Currency("NZD", 554, 2, "$"));
        put("PLN", new Currency("PLN", 985, 2, "zł"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("QAR", new Currency("QAR", 634, 2, "ر.ق"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("RON", new Currency("RON", 946, 2, "L"));
        put("RUB", new Currency("RUB", 643, 2, "руб."));
        put("RWF", new Currency("RWF", 646, 0, "Fr"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("SHP", new Currency("SHP", 654, 2, "£"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("XCD", new Currency("XCD", 951, 2, "$"));
        put("WST", new Currency("WST", 882, 2, "T"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("SAR", new Currency("SAR", 682, 2, "ر.س"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("RSD", new Currency("RSD", 941, 2, "дин."));
        put("SCR", new Currency("SCR", 690, 2, "₨"));
        put("SLL", new Currency("SLL", 694, 2, "Le"));
        put("SGD", new Currency("SGD", 702, 2, "$"));
        put("ANG", new Currency("ANG", 532, 2, "ƒ"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("SBD", new Currency("SBD", 90, 2, "$"));
        put("SOS", new Currency("SOS", 706, 2, "Sh"));
        put("ZAR", new Currency("ZAR", 710, 2, "R"));
        put("SSP", new Currency("SSP", 728, 2, "£"));
        put("EUR", new Currency("EUR", 978, 2, "€"));
        put("LKR", new Currency("LKR", 144, 2, "Rs"));
        put("SDG", new Currency("SDG", 938, 2, "£"));
        put("SRD", new Currency("SRD", 968, 2, "$"));
        put("NOK", new Currency("NOK", 578, 2, "kr"));
        put("SEK", new Currency("SEK", 752, 2, "kr"));
        put("CHF", new Currency("CHF", 756, 2, "Fr"));
        put("SYP", new Currency("SYP", 760, 2, "ل.س"));
        put("TWD", new Currency("TWD", 901, 2, "$"));
        put("TJS", new Currency("TJS", 972, 2, "ЅМ"));
        put("TZS", new Currency("TZS", 834, 2, "Sh"));
        put("THB", new Currency("THB", 764, 2, "฿"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("XOF", new Currency("XOF", 952, 0, "Fr"));
        put("NZD", new Currency("NZD", 554, 2, "$"));
        put("TOP", new Currency("TOP", 776, 2, "T$"));
        put("TTD", new Currency("TTD", 780, 2, "$"));
        put("TND", new Currency("TND", 788, 3, "د.ت"));
        put("TRY", new Currency("TRY", 949, 2, "NULL"));
        put("TMT", new Currency("TMT", 934, 2, "m"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("AUD", new Currency("AUD", 036, 2, "$"));
        put("UGX", new Currency("UGX", 800, 0, "Sh"));
        put("UAH", new Currency("UAH", 980, 2, "₴"));
        put("AED", new Currency("AED", 784, 2, "د.إ"));
        put("GBP", new Currency("GBP", 826, 2, "£"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("UYU", new Currency("UYU", 858, 2, "$"));
        put("UZS", new Currency("UZS", 860, 2, "лв"));
        put("VUV", new Currency("VUV", 548, 0, "Vt"));
        put("VND", new Currency("VND", 704, 0, "₫"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("USD", new Currency("USD", 840, 2, "$"));
        put("XPF", new Currency("XPF", 953, 0, "Fr"));
        put("MAD", new Currency("MAD", 504, 2, "د.م."));
        put("YER", new Currency("YER", 886, 2, "﷼"));
        put("ZMW", new Currency("ZMW", 967, 2, "ZK"));

      }
    };
    countryToCurrency = new HashMap<String, Currency>(200) {

      {
        put("AD", map.get("EUR"));
        put("AE", map.get("AED"));
        put("AF", map.get("AFN"));
        put("AG", map.get("XCD"));
        put("AI", map.get("XCD"));
        put("AL", map.get("ALL"));
        put("AM", map.get("AMD"));
        put("AO", map.get("AOA"));
        put("AR", map.get("ARS"));
        put("AS", map.get("USD"));
        put("AT", map.get("EUR"));
        put("AU", map.get("AUD"));
        put("AW", map.get("AWG"));
        put("AX", map.get("EUR"));
        put("AZ", map.get("AZN"));
        put("BA", map.get("BAM"));
        put("BB", map.get("BBD"));
        put("BD", map.get("BDT"));
        put("BE", map.get("EUR"));
        put("BF", map.get("XOF"));
        put("BG", map.get("BGN"));
        put("BH", map.get("BHD"));
        put("BI", map.get("BIF"));
        put("BJ", map.get("XOF"));
        put("BL", map.get("EUR"));
        put("BM", map.get("BMD"));
        put("BN", map.get("BND"));
        put("BO", map.get("BOB"));
        put("BQ", map.get("USD"));
        put("BR", map.get("BRL"));
        put("BS", map.get("BSD"));
        put("BT", map.get("INR"));
        put("BV", map.get("NOK"));
        put("BW", map.get("BWP"));
        put("BY", map.get("BYN"));
        put("BZ", map.get("BZD"));
        put("CA", map.get("CAD"));
        put("CC", map.get("AUD"));
        put("CD", map.get("CDF"));
        put("CF", map.get("XAF"));
        put("CG", map.get("XAF"));
        put("CH", map.get("CHF"));
        put("CI", map.get("XOF"));
        put("CK", map.get("NZD"));
        put("CL", map.get("CLP"));
        put("CM", map.get("XAF"));
        put("CN", map.get("CNY"));
        put("CO", map.get("COP"));
        put("CR", map.get("CRC"));
        put("CU", map.get("CUP"));
        put("CV", map.get("CVE"));
        put("CW", map.get("ANG"));
        put("CX", map.get("AUD"));
        put("CY", map.get("EUR"));
        put("CZ", map.get("CZK"));
        put("DE", map.get("EUR"));
        put("DJ", map.get("DJF"));
        put("DK", map.get("DKK"));
        put("DM", map.get("XCD"));
        put("DO", map.get("DOP"));
        put("DZ", map.get("DZD"));
        put("EC", map.get("USD"));
        put("EE", map.get("EUR"));
        put("EG", map.get("EGP"));
        put("EH", map.get("MAD"));
        put("ER", map.get("ERN"));
        put("ES", map.get("EUR"));
        put("ET", map.get("ETB"));
        put("FI", map.get("EUR"));
        put("FJ", map.get("FJD"));
        put("FK", map.get("FKP"));
        put("FM", map.get("USD"));
        put("FO", map.get("DKK"));
        put("FR", map.get("EUR"));
        put("GA", map.get("XAF"));
        put("GB", map.get("GBP"));
        put("GD", map.get("XCD"));
        put("GE", map.get("GEL"));
        put("GF", map.get("EUR"));
        put("GG", map.get("GGP"));
        put("GH", map.get("GHS"));
        put("GI", map.get("GIP"));
        put("GL", map.get("DKK"));
        put("GM", map.get("GMD"));
        put("GN", map.get("GNF"));
        put("GP", map.get("EUR"));
        put("GQ", map.get("XAF"));
        put("GR", map.get("EUR"));
        put("GS", map.get("GBP"));
        put("GT", map.get("GTQ"));
        put("GU", map.get("USD"));
        put("GW", map.get("XOF"));
        put("GY", map.get("GYD"));
        put("HK", map.get("HKD"));
        put("HM", map.get("AUD"));
        put("HN", map.get("HNL"));
        put("HR", map.get("HRK"));
        put("HT", map.get("HTG"));
        put("HU", map.get("HUF"));
        put("ID", map.get("IDR"));
        put("IE", map.get("EUR"));
        put("IL", map.get("ILS"));
        put("IM", map.get("GBP"));
        put("IN", map.get("INR"));
        put("IO", map.get("USD"));
        put("IQ", map.get("IQD"));
        put("IR", map.get("IRR"));
        put("IS", map.get("ISK"));
        put("IT", map.get("EUR"));
        put("JE", map.get("GBP"));
        put("JM", map.get("JMD"));
        put("JO", map.get("JOD"));
        put("JP", map.get("JPY"));
        put("KE", map.get("KES"));
        put("KG", map.get("KGS"));
        put("KH", map.get("KHR"));
        put("KI", map.get("AUD"));
        put("KM", map.get("KMF"));
        put("KN", map.get("XCD"));
        put("KP", map.get("KPW"));
        put("KR", map.get("KRW"));
        put("KW", map.get("KWD"));
        put("KY", map.get("KYD"));
        put("KZ", map.get("KZT"));
        put("LA", map.get("LAK"));
        put("LB", map.get("LBP"));
        put("LC", map.get("XCD"));
        put("LI", map.get("CHF"));
        put("LK", map.get("LKR"));
        put("LR", map.get("LRD"));
        put("LS", map.get("LSL"));
        put("LT", map.get("EUR"));
        put("LU", map.get("EUR"));
        put("LV", map.get("EUR"));
        put("LY", map.get("LYD"));
        put("MA", map.get("MAD"));
        put("MC", map.get("EUR"));
        put("MD", map.get("MDL"));
        put("ME", map.get("EUR"));
        put("MF", map.get("EUR"));
        put("MG", map.get("MGA"));
        put("MH", map.get("USD"));
        put("MK", map.get("MKD"));
        put("ML", map.get("XOF"));
        put("MM", map.get("MMK"));
        put("MN", map.get("MNT"));
        put("MO", map.get("MOP"));
        put("MP", map.get("USD"));
        put("MQ", map.get("EUR"));
        put("MR", map.get("MRO"));
        put("MS", map.get("XCD"));
        put("MT", map.get("EUR"));
        put("MU", map.get("MUR"));
        put("MV", map.get("MVR"));
        put("MW", map.get("MWK"));
        put("MX", map.get("MXN"));
        put("MY", map.get("MYR"));
        put("MZ", map.get("MZN"));
        put("NA", map.get("NAD"));
        put("NC", map.get("XPF"));
        put("NE", map.get("XOF"));
        put("NF", map.get("AUD"));
        put("NG", map.get("NGN"));
        put("NI", map.get("NIO"));
        put("NL", map.get("EUR"));
        put("NO", map.get("NOK"));
        put("NP", map.get("NPR"));
        put("NR", map.get("AUD"));
        put("NU", map.get("NZD"));
        put("NZ", map.get("NZD"));
        put("OM", map.get("OMR"));
        put("PA", map.get("PAB"));
        put("PE", map.get("PEN"));
        put("PF", map.get("XPF"));
        put("PG", map.get("PGK"));
        put("PH", map.get("PHP"));
        put("PK", map.get("PKR"));
        put("PL", map.get("PLN"));
        put("PM", map.get("EUR"));
        put("PN", map.get("NZD"));
        put("PR", map.get("USD"));
        put("PS", map.get("JOD"));
        put("PT", map.get("EUR"));
        put("PW", map.get("USD"));
        put("PY", map.get("PYG"));
        put("QA", map.get("QAR"));
        put("RE", map.get("EUR"));
        put("RO", map.get("RON"));
        put("RS", map.get("RSD"));
        put("RU", map.get("RUB"));
        put("RW", map.get("RWF"));
        put("SA", map.get("SAR"));
        put("SB", map.get("SBD"));
        put("SC", map.get("SCR"));
        put("SD", map.get("SDG"));
        put("SE", map.get("SEK"));
        put("SG", map.get("SGD"));
        put("SH", map.get("SHP"));
        put("SI", map.get("EUR"));
        put("SJ", map.get("NOK"));
        put("SK", map.get("EUR"));
        put("SL", map.get("SLL"));
        put("SM", map.get("EUR"));
        put("SN", map.get("XOF"));
        put("SO", map.get("SOS"));
        put("SR", map.get("SRD"));
        put("SS", map.get("SSP"));
        put("ST", map.get("STD"));
        put("SV", map.get("USD"));
        put("SX", map.get("ANG"));
        put("SY", map.get("SYP"));
        put("SZ", map.get("SZL"));
        put("TC", map.get("USD"));
        put("TD", map.get("XAF"));
        put("TF", map.get("EUR"));
        put("TG", map.get("XOF"));
        put("TH", map.get("THB"));
        put("TJ", map.get("TJS"));
        put("TK", map.get("NZD"));
        put("TL", map.get("USD"));
        put("TM", map.get("TMT"));
        put("TN", map.get("TND"));
        put("TO", map.get("TOP"));
        put("TR", map.get("TRY"));
        put("TT", map.get("TTD"));
        put("TV", map.get("AUD"));
        put("TW", map.get("TWD"));
        put("TZ", map.get("TZS"));
        put("UA", map.get("UAH"));
        put("UG", map.get("UGX"));
        put("UM", map.get("USD"));
        put("US", map.get("USD"));
        put("UY", map.get("UYU"));
        put("UZ", map.get("UZS"));
        put("VA", map.get("EUR"));
        put("VC", map.get("XCD"));
        put("VE", map.get("VEF"));
        put("VG", map.get("USD"));
        put("VI", map.get("USD"));
        put("VN", map.get("VND"));
        put("VU", map.get("VUV"));
        put("WF", map.get("XPF"));
        put("WS", map.get("EUR"));
        put("YE", map.get("YER"));
        put("YT", map.get("EUR"));
        put("ZA", map.get("ZAR"));
        put("ZM", map.get("ZMW"));
        put("ZW", map.get("USD"));

      }
    };
  }

  public static Currency getInstance(final Locale locale) {
    if (locale == null)
      throw new NullPointerException("locale is null");
    final String code = locale.getCountry();
    if (code == null)
      throw new NullPointerException("country is null");
    final Currency ret = countryToCurrency.get(code);
    if (ret == null)
      throw new IllegalArgumentException(code + " does not have a currency");
    return ret;
  }

  public static Currency getInstance(final String currencyCode) {
    return map.get(currencyCode);
  }

  @SuppressWarnings("unused")
  private final int    numCode;
  private final String alphaCode;
  private final int    digits;
  private final String symbol;

  private Currency(
    final String newAlphaCode, final int newNumCode, final int newDigits, final String newSymbol
    ) {
    alphaCode = newAlphaCode;
    numCode = newNumCode;
    digits = newDigits;
    symbol = newSymbol;
  }

  public String getCurrencyCode() {
    return alphaCode;
  }

  public int getDefaultFractionDigits() {
    return digits;
  }

  public String getSymbol() {
    return symbol;
  }

  public String getSymbol(final Locale locale) {
    return symbol;
  }

  @Override
  public String toString() {
    return getCurrencyCode();
  }
}
